version: '3'

services:
  database:
    image: 'postgres'
    ports:
      - 5432:5432
    env_file:
      - database.env
    volumes:
      - postgresql:/var/lib/postgresql/data/

volumes:
  postgresql:
